# Generated by Django 3.2.7 on 2021-10-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211008_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
